/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d4f828d2e8ab75d05c7281e
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE homeBaseService PLEASE EDIT ../home.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Home } from '../../domain/alkiapp_db/home';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Home.service.ts
 */

/*
 * SCHEMA DB Home
 *
	{
		address: {
			type: 'String',
			required : true
		},
		available: {
			type: 'Integer',
			required : true
		},
		bathrooms: {
			type: 'Integer',
			required : true
		},
		city: {
			type: 'String',
			required : true
		},
		description: {
			type: 'String'
		},
		images: {
			type: 'String',
			required : true
		},
		internet: {
			type: 'Integer',
			required : true
		},
		onlyfor: {
			type: 'Integer',
			required : true
		},
		owner: {
			type: 'Integer',
			required : true
		},
		price: {
			type: 'Integer',
			required : true
		},
		rooms: {
			type: 'Integer',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class HomeBaseService {

    contextUrl: string = environment.endpoint + '/home';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * HomeService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Home): Observable<Home> {
        return this.http
            .post<Home>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * HomeService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * HomeService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Home> {
        return this.http
            .get<Home>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * HomeService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Home[]> {
        return this.http
            .get<Home[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * HomeService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Home): Observable<Home> {
        return this.http
            .post<Home>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
